# The Site Configuration
# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: ko-KR

# Change to your timezone
timezone: Asia/Seoul

# jekyll-seo-tag settings
title: HeyFinOps
tagline: Cloud FinOps 기술 블로그
description: >-
  AWS, Azure, GCP 클라우드 비용 최적화와 FinOps 실무 경험을 공유합니다.

# Fill in the protocol & hostname for your site.
# e.g. 'https://username.github.io'
url: "https://heyfinops.github.io"

github:
  username: # GitHub username

social:
  name: HeyFinOps
  links:
    # - https://twitter.com/
    # - https://github.com/username

# Web Analytics Settings
analytics:
  google:
    id: # Google Analytics ID

# Prefer color scheme setting
# Options: light, dark
theme_mode: dark

# The CDN endpoint for images
# img_cdn: ""

# Avatar on sidebar
avatar: ""

# The URL of the site-wide social preview image
# social_preview_image: /path/to/image

# Boolean to enable TOC (Table of Contents)
toc: true

comments:
  # Global switch for the post-comment system
  active: # giscus, disqus, utterances
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:

# Self-hosted static assets
assets:
  self_host:
    enabled: false

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _tabs
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
